#define DEF_SLEEP_MS_0 (250U)

enum TEST_GPIO_OUTPUT
{
    TEST_GPIO_OUTPUT_0 = 6U,
    TEST_GPIO_OUTPUT_1,
    TEST_GPIO_OUTPUT_2,
    TEST_GPIO_OUTPUT_3,
    TEST_GPIO_OUTPUT_LENGTH
};

enum TEST_GPIO_INPUT
{
    TEST_GPIO_INPUT_0 = 10U,
    TEST_GPIO_INPUT_1,
    TEST_GPIO_INPUT_2,
    TEST_GPIO_INPUT_3,
    TEST_GPIO_INPUT_LENGTH
};